# Primeiro trato célula a célula e depois compilo como função no arquivo PreProcessing.py

# Normalização

In [4]:
import pandas as pd
df_vagas = pd.read_csv(r'C:\Users\RodrigoPintoMesquita\Documents\GitHub\PB_TP_X\app\data\raw\vagas.csv')
df_vagas['empresa_contratante'] = df_vagas['empresa_contratante'].str.upper()
df_vagas['empresa_contratante'] = df_vagas['empresa_contratante'].replace('CLIENTE', 'EMPRESA CONFIDENCIAL').replace('CONFIDENCIAL', 'EMPRESA CONFIDENCIAL').replace('********', 'EMPRESA CONFIDENCIAL')

df_vagas['data_anuncio'] = pd.to_datetime(df_vagas['data_anuncio']).dt.date

#Adicionar uma coluna de região (Sul, Sudeste, Centro-Oeste, Nordeste, Norte) a partir da coluna de estado
df_vagas['regiao'] = df_vagas['estado'].map({'AC': 'Norte', 'AL': 'Nordeste', 'AP': 'Norte', 'AM': 'Norte', 'BA': 'Nordeste', 'CE': 'Nordeste', 'DF': 'Centro-Oeste', 'ES': 'Sudeste', 'GO': 'Centro-Oeste', 'MA': 'Nordeste', 'MT': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MG': 'Sudeste', 'PA': 'Norte', 'PB': 'Nordeste', 'PR': 'Sul', 'PE': 'Nordeste', 'PI': 'Nordeste', 'RJ': 'Sudeste', 'RN': 'Nordeste', 'RS': 'Sul', 'RO': 'Norte', 'RR': 'Norte', 'SC': 'Sul', 'SP': 'Sudeste', 'SE': 'Nordeste', 'TO': 'Norte'})

## Classificar as vagas nas categorias: Analista, Cientista ou Engenheiro de Dados

In [146]:
#-----------Classificar as vagas nas categorias: Analista, Cientista ou Engenheiro de Dados------------
lista_vagas = df_vagas.titulo_resumo.unique()

de_para_vagas = {}

for vaga in lista_vagas:
    if 'eng' in vaga and 'dados' in vaga:
        norm = 'engenheiro'
    elif 'anal' in vaga and 'dados' in vaga:
        norm = 'analista'
    elif 'cientista' in vaga or 'ciencia' in vaga:
        norm = 'cientista'
    elif 'anal' in vaga and 'bi' in vaga:
        norm = 'analista'
    elif 'intell' in vaga:
        norm = 'analista'        
    else:
        norm = 'outros'

    de_para_vagas[vaga] = norm

#Join para trazer a classificação das vagas
df_vagas['perfil_vaga'] = df_vagas['titulo_resumo'].map(de_para_vagas)

#Retirar  as duas vagas que ficaram como "outros", pois eram de analistas de sistemas
df_vagas = df_vagas[df_vagas['perfil_vaga'] != 'outros']

df_vagas.head(3)

,id_vaga,data_anuncio,titulo_vaga,titulo_resumo,faixa_salarial,empresa_contratante,estado,cidade,url,descricao,beneficios,regimeContrato,regiao,perfil_vaga
0,30077919,2024-08-16,Analista de Dados - Júnior,analista-de-dados-junior,não disponível,CARTÃO DE TODOS,MG,Ipatinga,/vagas/analista-de-dados-junior/30077919/,"Para agregar nosso time, suas principais ativi...","['Seguro Saúde', 'Assistência Médica / Medicin...",CLT (Efetivo),Sudeste,analista
1,30045699,2024-08-21,Cientista de Dados Sênior,cientista-de-dados-senior,não disponível,DECISION,SP,São Paulo,/vagas/cientista-de-dados-senior/30045699/,Skills / Atividades: Conhecimentos em Conhecim...,[],NaN,Sudeste,cientista
2,30600767,2024-10-07,Analista de Dados em Excel,analista-de-dados-em-excel,não disponível,JETER CONSULTING,SP,São Paulo,/vagas/analista-de-dados-em-excel/30600767/,Com experiência comprovada como Analista de Si...,"['Convênio com Farmácia', 'Vale Transporte']",CLT (Efetivo),Sudeste,analista

## Descobrindo a Senioridade do Cargo

In [147]:
#-----------Descobrindo a Serionidade da Vaga (Junior, Pleno, Senior)------------

lista_vagas = df_vagas.titulo_resumo.unique()

nivel_cargo = {}

for vaga in lista_vagas:
    if 'senior' in vaga or 'sr' in vaga:
        nivel = 'senior'
    elif 'junior' in vaga or 'jr' in vaga:
        nivel = 'junior'   
    else:
        nivel = 'pleno'

    nivel_cargo[vaga] = nivel

#Join para trazer a classificação das vagas
df_vagas['nivel_cargo'] = df_vagas['titulo_resumo'].map(nivel_cargo)

df_vagas.head(3)

,id_vaga,data_anuncio,titulo_vaga,titulo_resumo,faixa_salarial,empresa_contratante,estado,cidade,url,descricao,beneficios,regimeContrato,regiao,perfil_vaga,nivel_cargo
0,30077919,2024-08-16,Analista de Dados - Júnior,analista-de-dados-junior,não disponível,CARTÃO DE TODOS,MG,Ipatinga,/vagas/analista-de-dados-junior/30077919/,"Para agregar nosso time, suas principais ativi...","['Seguro Saúde', 'Assistência Médica / Medicin...",CLT (Efetivo),Sudeste,analista,junior
1,30045699,2024-08-21,Cientista de Dados Sênior,cientista-de-dados-senior,não disponível,DECISION,SP,São Paulo,/vagas/cientista-de-dados-senior/30045699/,Skills / Atividades: Conhecimentos em Conhecim...,[],NaN,Sudeste,cientista,senior
2,30600767,2024-10-07,Analista de Dados em Excel,analista-de-dados-em-excel,não disponível,JETER CONSULTING,SP,São Paulo,/vagas/analista-de-dados-em-excel/30600767/,Com experiência comprovada como Analista de Si...,"['Convênio com Farmácia', 'Vale Transporte']",CLT (Efetivo),Sudeste,analista,pleno

## Tirando a média a partir da Faixa Salarial

In [148]:
#--------------Ajustando a média salarial a partir da faixa salarial---------------------
import re

for i,row in df_vagas.iterrows():
    if pd.isnull(row.faixa_salarial):
        row.salario = None
    else:
        pattern = r"R\$ ([\d\.]+,\d{2}) a R\$ ([\d\.]+,\d{2})"
        match = re.search(pattern, row.faixa_salarial)
        if match:
            minimo = float(match.group(1).replace('.','').replace(',','.'))
            maximo = float(match.group(2).replace('.','').replace(',','.'))
            media = round((minimo + maximo) / 2, 0)
        else:
            media = None

        df_vagas.at[i, 'salario'] = media

In [149]:
df_vagas.to_csv(r'C:\Users\RodrigoPintoMesquita\Documents\GitHub\PB_TP_X\app\data\processed\vagas_norm.csv', index=False)
df_vagas.head(3)

,id_vaga,data_anuncio,titulo_vaga,titulo_resumo,faixa_salarial,empresa_contratante,estado,cidade,url,descricao,beneficios,regimeContrato,regiao,perfil_vaga,nivel_cargo,salario
0,30077919,2024-08-16,Analista de Dados - Júnior,analista-de-dados-junior,não disponível,CARTÃO DE TODOS,MG,Ipatinga,/vagas/analista-de-dados-junior/30077919/,"Para agregar nosso time, suas principais ativi...","['Seguro Saúde', 'Assistência Médica / Medicin...",CLT (Efetivo),Sudeste,analista,junior,None
1,30045699,2024-08-21,Cientista de Dados Sênior,cientista-de-dados-senior,não disponível,DECISION,SP,São Paulo,/vagas/cientista-de-dados-senior/30045699/,Skills / Atividades: Conhecimentos em Conhecim...,[],NaN,Sudeste,cientista,senior,None
2,30600767,2024-10-07,Analista de Dados em Excel,analista-de-dados-em-excel,não disponível,JETER CONSULTING,SP,São Paulo,/vagas/analista-de-dados-em-excel/30600767/,Com experiência comprovada como Analista de Si...,"['Convênio com Farmácia', 'Vale Transporte']",CLT (Efetivo),Sudeste,analista,pleno,None

## Buscando os requisitos ferramentais em cada vaga

In [ ]:
#-----------------------------Buscando os requisitos ferramentais em cada vaga-----------------------------

df_vagas = pd.read_csv(r'C:\Users\RodrigoPintoMesquita\Documents\GitHub\PB_TP_X\app\data\processed\vagas_norm.csv')
df_tools = pd.read_csv(r'C:\Users\RodrigoPintoMesquita\Documents\GitHub\PB_TP_X\app\data\processed\ferramentas.csv')
conjunto_tools = set(df_tools['FERRAMENTAS'].str.upper())
requisitos = []

for i, row in df_vagas.iterrows():
    #remover pontuações do campo de descrição
    descricao = row['descricao'].replace(',', ' ').replace('.', ' ').replace(';', ' ').replace(':', ' ').replace('(', ' ').replace(')', ' ')
    
    #transformar a descrição em uma conjunto de palavras
    desc = descricao.upper().split()
    conjunto_desc = set(desc)

    #verificar a intersecção entre as palavras da descrição e as palavras do conjunto de ferramentas
    interseccao = conjunto_desc.intersection(conjunto_tools)

    #converter a interseccao em uma lista
    lista_interseccao = list(interseccao)

    #criar uma lista de tuplas com o id da vaga e a ferramenta
    for tool in lista_interseccao:
        id_vaga = row['id_vaga']
        requisitos.append([id_vaga, tool])

df_requisitos = pd.DataFrame(requisitos, columns=['id_vaga', 'tool'])
df_requisitos.to_csv(r'C:\Users\RodrigoPintoMesquita\Documents\GitHub\PB_TP_X\app\data\processed\requisitos.csv', index=False)

# Criando o arquivo com as funções

In [15]:
%%writefile 'C:\Users\RodrigoPintoMesquita\Documents\GitHub\PB_TP_X\app\services\functions_dataPreProcessing.py'


import pandas as pd
import re

def Pre_Processamento_Df_Vagas(path_csv_vagas, path_csv_vagas_norm):
    df_vagas = pd.read_csv(path_csv_vagas)
    df_vagas['empresa_contratante'] = df_vagas['empresa_contratante'].str.upper()
    df_vagas['empresa_contratante'] = df_vagas['empresa_contratante'].replace('CLIENTE', 'EMPRESA CONFIDENCIAL').replace('CONFIDENCIAL', 'EMPRESA CONFIDENCIAL').replace('********', 'EMPRESA CONFIDENCIAL')

    df_vagas['data_anuncio'] = pd.to_datetime(df_vagas['data_anuncio']).dt.date

    #Adicionar uma coluna de região (Sul, Sudeste, Centro-Oeste, Nordeste, Norte) a partir da coluna de estado
    df_vagas['regiao'] = df_vagas['estado'].map({'AC': 'Norte', 'AL': 'Nordeste', 'AP': 'Norte', 'AM': 'Norte', 'BA': 'Nordeste', 'CE': 'Nordeste', 'DF': 'Centro-Oeste', 'ES': 'Sudeste', 'GO': 'Centro-Oeste', 'MA': 'Nordeste', 'MT': 'Centro-Oeste', 'MS': 'Centro-Oeste', 'MG': 'Sudeste', 'PA': 'Norte', 'PB': 'Nordeste', 'PR': 'Sul', 'PE': 'Nordeste', 'PI': 'Nordeste', 'RJ': 'Sudeste', 'RN': 'Nordeste', 'RS': 'Sul', 'RO': 'Norte', 'RR': 'Norte', 'SC': 'Sul', 'SP': 'Sudeste', 'SE': 'Nordeste', 'TO': 'Norte'})




    #----------- Classificar as vagas nas categorias: Analista, Cientista ou Engenheiro de Dados------------
    lista_vagas = df_vagas.titulo_resumo.unique()

    de_para_vagas = {}

    for vaga in lista_vagas:
        if 'eng' in vaga and 'dados' in vaga:
            norm = 'engenheiro'
        elif 'anal' in vaga and 'dados' in vaga:
            norm = 'analista'
        elif 'cientista' in vaga or 'ciencia' in vaga:
            norm = 'cientista'
        elif 'anal' in vaga and 'bi' in vaga:
            norm = 'analista'
        elif 'intell' in vaga:
            norm = 'analista'        
        else:
            norm = 'outros'

        de_para_vagas[vaga] = norm

    #Join para trazer a classificação das vagas
    df_vagas['perfil_vaga'] = df_vagas['titulo_resumo'].map(de_para_vagas)

    #Retirar  as duas vagas que ficaram como "outros", pois eram de analistas de sistemas
    df_vagas = df_vagas[df_vagas['perfil_vaga'] != 'outros']





    #-----------Descobrindo a Serionidade da Vaga (Junior, Pleno, Senior)------------

    lista_vagas = df_vagas.titulo_resumo.unique()

    nivel_cargo = {}

    for vaga in lista_vagas:
        if 'senior' in vaga or 'sr' in vaga:
            nivel = 'senior'
        elif 'junior' in vaga or 'jr' in vaga:
            nivel = 'junior'   
        else:
            nivel = 'pleno'

        nivel_cargo[vaga] = nivel

    #Join para trazer a classificação das vagas
    df_vagas['nivel_cargo'] = df_vagas['titulo_resumo'].map(nivel_cargo)



    #--------------Ajustando a média salarial a partir da faixa salarial---------------------

    for i,row in df_vagas.iterrows():
        if pd.isnull(row.faixa_salarial):
            row.salario = None
        else:
            pattern = r"R\$ ([\d\.]+,\d{2}) a R\$ ([\d\.]+,\d{2})"
            match = re.search(pattern, row.faixa_salarial)
            if match:
                minimo = float(match.group(1).replace('.','').replace(',','.'))
                maximo = float(match.group(2).replace('.','').replace(',','.'))
                media = round((minimo + maximo) / 2, 0)
            else:
                media = None

            df_vagas.at[i, 'salario'] = media


    df_vagas.to_csv(path_csv_vagas_norm, index=False)




#-----------------------------Buscando os requisitos ferramentais em cada vaga-----------------------------
def Pre_Processamento_Df_Requisitos(path_csv_lista_ferramentas, path_csv_vagas, path_csv_requisitos):

    df_vagas = pd.read_csv(path_csv_vagas)
    df_lista_ferramentas = pd.read_csv(path_csv_lista_ferramentas)
    conjunto_tools = set(df_lista_ferramentas['FERRAMENTAS'].str.upper())
    requisitos = []

    for i, row in df_vagas.iterrows():
        #remover pontuações do campo de descrição
        descricao = row['descricao'].replace(',', ' ').replace('.', ' ').replace(';', ' ').replace(':', ' ').replace('(', ' ').replace(')', ' ')
        
        #transformar a descrição em uma conjunto de palavras
        desc = descricao.upper().split()
        conjunto_desc = set(desc)

        #verificar a intersecção entre as palavras da descrição e as palavras do conjunto de ferramentas
        interseccao = conjunto_desc.intersection(conjunto_tools)

        #converter a interseccao em uma lista
        lista_interseccao = list(interseccao)

        #criar uma lista de tuplas com o id da vaga e a ferramenta
        for tool in lista_interseccao:
            id_vaga = row['id_vaga']
            requisitos.append([id_vaga, tool])

    df_requisitos = pd.DataFrame(requisitos, columns=['id_vaga', 'tool'])
    df_requisitos.to_csv(path_csv_requisitos)

Overwriting C:\Users\RodrigoPintoMesquita\Documents\GitHub\PB_TP_X\app\services\functions_dataPreProcessing.py